[package]
name = "xrml-fee-config"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]

[dependencies]
sr-std = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }

[features]
default = ["std"]
std = [
    "sr-std/std",
    "sr-primitives/std",
]
