[package]
name = "chainx"
version = "0.3.0"
authors = ["Chainpool <https://www.chainx.org>"]

[dependencies]
chainx-cli = { path = "./cli" }
ctrlc = { version = "3.0", features = ["termination"] }
error-chain = "0.12"
futures = "0.1.17"

# bitcoin-rust
primitives = { git = "https://github.com/chainx-org/bitcoin-rust" }
chain = { git = "https://github.com/chainx-org/bitcoin-rust" }
keys = { git = "https://github.com/chainx-org/bitcoin-rust" }

[workspace]
members = [
    "primitives",
    "executor",
    "runtime",
    "cli",

    # xrml
    "xrml/xsystem",
    "xrml/xsupport",
    "xrml/xaccounts",
    # xrml/xfee
    "xrml/xfee/manager",
    # xrml/assets
    "xrml/xassets/assets",
]
