[package]
name = "chainx"
version = "0.9.0"
build = "build.rs"
authors = ["Chainpool <https://www.chainx.org>"]

[[bin]]
name = "chainx"
path = "src/main.rs"

[dependencies]
chainx-cli = { path = "./cli" }
ctrlc = { version = "3.0", features = ["termination"] }
error-chain = "0.12"
futures = "0.1.17"

# bitcoin-rust
primitives = { git = "https://github.com/chainx-org/bitcoin-rust" }
chain = { git = "https://github.com/chainx-org/bitcoin-rust" }
keys = { git = "https://github.com/chainx-org/bitcoin-rust" }

[features]
msgbus-redis = [
	"chainx-cli/msgbus-redis"
]

msgbus-redis-keyhash = [
	"msgbus-redis",
	"chainx-cli/msgbus-redis-keyhash",
]

cache-lru = [
	"chainx-cli/cache-lru"
]

[workspace]
members = [
    "primitives",
    "executor",
    "runtime",
    "cli",
    "rpc",
    "rpc-servers",
    "runtime-api",
    "xr-primitives",

    # xrml
    "xrml/xsystem",
    "xrml/xsupport",
    "xrml/xaccounts",
    "xrml/xsession",
    "xrml/xgrandpa",
    "xrml/xaura",
    "xrml/xmultisig",
    # xrml/xfee
    "xrml/xfee/manager",
    # xrml/assets
    "xrml/xassets/assets",
    "xrml/xdex/spot",
    "xrml/xassets/records",
    "xrml/xassets/process",
    # xrml/mining
    "xrml/xmining/staking",
    "xrml/xmining/tokens",
    "xrml/xbridge/bitcoin",
    "xrml/xbridge/sdot",
]

[build-dependencies]
vergen = "3"

