[package]
name = "xrml-xassets-records"
version = "0.4.0"
authors = ["Chainpool <https://www.chainx.org>"]

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-std = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-io = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-support = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-system = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-balances = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-consensus = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-timestamp = { git = "https://github.com/chainpool/substrate", default_features = false }

# chainx runtime
xr-primitives = { path = "../../../xr-primitives", default_features = false }
# xrml module
xrml-xsupport = { path = "../../xsupport", default_features = false }
xrml-xassets-assets = { path = "../assets", default_features = false }


[features]
default = ["std"]
std=[
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    "substrate-primitives/std",
    "sr-std/std",
    "sr-io/std",
    "sr-primitives/std",
    "srml-support/std",
    "srml-system/std",
    "srml-balances/std",
    "srml-consensus/std",
    "srml-timestamp/std",
    # chainx runtime
    "xr-primitives/std",
    # xrml module
    "xrml-xsupport/std",
    "xrml-xassets-assets/std",
]
