[package]
name = "substrate-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.12"
jsonrpc-core = { git="https://github.com/paritytech/jsonrpc.git" }
jsonrpc-macros = { git="https://github.com/paritytech/jsonrpc.git" }
jsonrpc-pubsub = { git="https://github.com/paritytech/jsonrpc.git" }
log = "0.4"
parking_lot = "0.4"
parity-codec = "2.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
keys = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
chain = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
script = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }

substrate-client = { git = "https://github.com/chainpool/substrate" }
substrate-executor = { git = "https://github.com/chainpool/substrate" }
substrate-network = { git = "https://github.com/chainpool/substrate" }
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
substrate-transaction-pool = { git = "https://github.com/chainpool/substrate" }
substrate-state-machine = { git = "https://github.com/chainpool/substrate" }
sr-primitives = { git = "https://github.com/chainpool/substrate" }
sr-version = { git = "https://github.com/chainpool/substrate" }
srml-support = { git = "https://github.com/chainpool/substrate" }
srml-session = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-balances = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-timestamp = { git = "https://github.com/chainpool/substrate", default_features = false }

tokio = "0.1.7"
chainx-primitives = { path = "../primitives" }
xrml-xassets-assets = { path = "../xrml/xassets/assets" }
xrml-xassets-records = { path = "../xrml/xassets/records" }
xrml-xaccounts = { path = "../xrml/xaccounts" }
xrml-mining-staking = { path = "../xrml/xmining/staking" }
xrml-mining-tokens = { path = "../xrml/xmining/tokens" }
xrml-xsupport = { path = "../xrml/xsupport"  }
xrml-xdex-spot = { path = "../xrml/xdex/spot"  }
xrml-bridge-bitcoin = { path = "../xrml/xbridge/bitcoin"  }
chainx-runtime = {path = "../runtime"}

runtime-api = {path = "../runtime-api"}

[dev-dependencies]
assert_matches = "1.1"
substrate-test-client = { git = "https://github.com/chainpool/substrate" }
substrate-consensus-common = { git = "https://github.com/chainpool/substrate" }
rustc-hex = "2.0"
hex-literal = "0.1"
