[package]
name = "chainx-runtime"
version = "0.3.0"
authors = ["Chainpool <http://www.chainx.org>"]

[dependencies]
rustc-hex = "1.0"
hex-literal = "0.1.0"
safe-mix = { version = "1.0", default_features = false}
serde = { version = "1.0", default_features = false }
parity-codec = "2.1"
parity-codec-derive = "2.1"

substrate-client = { git = "https://github.com/chainpool/substrate" }
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
substrate-finality-grandpa-primitives = { git = "https://github.com/chainpool/substrate" }
substrate-consensus-aura-primitives = { git = "https://github.com/chainpool/substrate" }

sr-primitives = { git = "https://github.com/chainpool/substrate" }
sr-version = { git = "https://github.com/chainpool/substrate" }
sr-std = { git = "https://github.com/chainpool/substrate" }

srml-support = { git = "https://github.com/chainpool/substrate" }
srml-system = { git = "https://github.com/chainpool/substrate" }
srml-balances = { git = "https://github.com/chainpool/substrate" }
srml-timestamp = { git = "https://github.com/chainpool/substrate" }
srml-consensus = { git = "https://github.com/chainpool/substrate" }
srml-session = { git = "https://github.com/chainpool/substrate" }
srml-grandpa = { git = "https://github.com/chainpool/substrate" }
srml-aura = { git = "https://github.com/chainpool/substrate" }

srml-contract = { git = "https://github.com/chainpool/substrate" }
srml-council = { git = "https://github.com/chainpool/substrate" }
srml-democracy = { git = "https://github.com/chainpool/substrate" }
srml-treasury = { git = "https://github.com/chainpool/substrate" }

# chainx
chainx-primitives = { path = "../primitives" }

# chainx runtime module
xrml-xsystem = { path = "../xrml/xsystem" }
xrml-executive = { path = "../xrml/xexecutive" }
# fee
xrml-fee-manager = { path = "../xrml/xfee/manager" }
# assets
xrml-xassets-assets = { path = "../xrml/xassets/assets" }


[features]
default = ["std"]
std = [
    "serde/std",
    "safe-mix/std",
    "parity-codec/std",
    "substrate-primitives/std",
    "substrate-consensus-aura-primitives/std",

    # substrate runtime module
    "sr-primitives/std",
    "sr-version/std",
    "sr-std/std",

    "srml-support/std",
    "srml-system/std",
    "srml-balances/std",
    "srml-timestamp/std",
    "srml-consensus/std",
    "srml-session/std",
    "srml-grandpa/std",
    "srml-aura/std",

    "srml-contract/std",
    "srml-council/std",
    "srml-democracy/std",
    "srml-treasury/std",
    # chainx
    "chainx-primitives/std",
    # chainx runtime
    "xrml-xsystem/std",
    "xrml-executive/std",
    # fee
    "xrml-fee-manager/std",
    # asset
    "xrml-xassets-assets/std"
]
