[package]
name = "xrml-xmultisig"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-std = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-io = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-support = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-system = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-balances = { git = "https://github.com/chainpool/substrate", default_features = false }

xr-primitives = { path = "../../xr-primitives", default_features = false }
xsupport = { package = "xrml-xsupport", path = "../xsupport", default_features = false }
xassets = { package = "xrml-xassets-assets", path = "../xassets/assets", default_features = false }
xaccounts = { package = "xrml-xaccounts", path = "../xaccounts", default_features = false }
xbitcoin = { package = "xrml-bridge-bitcoin", path = "../xbridge/bitcoin", default_features = false }
xstaking = { package = "xrml-mining-staking", path = "../xmining/staking", default-features = false }

[dev-dependencies]
sr-io = { git = "https://github.com/chainpool/substrate" }

[features]
default = ["std"]
std=[
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    "sr-std/std",
    "sr-primitives/std",
    "srml-support/std",
    "srml-system/std",
    "srml-balances/std",
    # xrml
    "xr-primitives/std",
    "xsupport/std",
    "xassets/std",
    "xaccounts/std",
    "xbitcoin/std",
    "xstaking/std",
]
