[package]
name = "chainx-cli"
version = "0.1.0"
description = "ChainX node implementation in Rust."

[dependencies]
log = "0.4"
tokio = "0.1.7"
exit-future = "0.1"
hex-literal = "0.1"
parity-codec = { version = "2.1" }
slog = "^2"
# substrate
substrate-cli = { git = "https://github.com/chainpool/substrate" }
substrate-client = { git = "https://github.com/chainpool/substrate" }
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
substrate-basic-authorship = { git = "https://github.com/chainpool/substrate" }
substrate-service = { git = "https://github.com/chainpool/substrate" }
substrate-transaction-pool = { git = "https://github.com/chainpool/substrate" }
substrate-network = { git = "https://github.com/chainpool/substrate" }
substrate-consensus-aura = { git = "https://github.com/chainpool/substrate" }
substrate-finality-grandpa = { git = "https://github.com/chainpool/substrate" }
substrate-keyring = { git = "https://github.com/chainpool/substrate" }

sr-io = { git = "https://github.com/chainpool/substrate" }
sr-primitives = { git = "https://github.com/chainpool/substrate" }

chainx-runtime = { path = "../runtime" }
chainx-primitives = { path = "../primitives" }

chainx-executor = { path = "../executor" }

# bitcoin
primitives = { git = "https://github.com/chainx-org/bitcoin-rust" }
chain = { git = "https://github.com/chainx-org/bitcoin-rust" }
keys = { git = "https://github.com/chainx-org/bitcoin-rust" }
substrate-rpc-servers = { path = "../rpc-servers" }
structopt = "0.2.13"
base58 = "0.1"

[dev-dependencies]
substrate-service-test = { git = "https://github.com/chainpool/substrate" }

[features]
msgbus-redis = [
    "substrate-cli/msgbus-redis"
]
msgbus-redis-keyhash = [
    "msgbus-redis",
    "substrate-cli/msgbus-redis-keyhash",
]
cache-lru = [
    "substrate-cli/cache-lru"
]