[package]
name = "xrml-mining-staking"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default_features = false}
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }
substrate-keyring = { git = "https://github.com/chainpool/substrate", optional = true }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default_features = false }
runtime_io = { package = "sr-io", git = "https://github.com/chainpool/substrate", default_features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default_features = false }
runtime_support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default_features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default_features = false }
balances = { package = "srml-balances", git = "https://github.com/chainpool/substrate", default_features = false }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", default_features = false }
indices = { package = "srml-indices", git = "https://github.com/chainpool/substrate", default_features = false }
timestamp = { package ="srml-timestamp", git = "https://github.com/chainpool/substrate", default_features = false }

# chainx runtime
xr-primitives = { path = "../../../xr-primitives", default_features = false }
# xrml
xsystem = { package = "xrml-xsystem", path = "../../xsystem", default-features = false }
xaccounts = { package = "xrml-xaccounts", path = "../../xaccounts", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default_features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xassets/assets", default_features = false }
xbitcoin = { package = "xrml-bridge-bitcoin", path = "../../xbridge/bitcoin", default-features = false }
xrecords = { package = "xrml-xassets-records", path = "../../xassets/records", default-features = false }
session = { package = "xrml-session", path = "../../xsession", default_features = false }

[dev-dependencies]
fee_manager = { package = "xrml-fee-manager", path = "../../xfee/manager", default-features = false }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "safe-mix/std",
    "substrate-keyring",
    "parity-codec/std",
    "substrate-primitives/std",
    "rstd/std",
    "runtime_io/std",
    "system/std",
    "primitives/std",
    "runtime_support/std",
    "primitives/std",
    "balances/std",
    "session/std",
    "system/std",
    "indices/std",
    "timestamp/std",
    # chainx runtime
    "xr-primitives/std",
    # xrml
    "xsystem/std",
    "balances/std",
    "xaccounts/std",
    "xsupport/std",
    "xassets/std",
    "xrecords/std",
    "xbitcoin/std",
]
