[package]
name = "xrml-xassets-process"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]


[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "2.0", default-features = false }
parity-codec-derive = { version = "2.0", default-features = false }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-std = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-io = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-support = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-system = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-balances = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-timestamp = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-consensus = { git = "https://github.com/chainpool/substrate", default_features = false }

# xrml module
xrml-xassets-assets = { path = "../assets", default_features = false }
xrml-xassets-records = { path = "../records", default_features = false }
# bridge
xrml-xbridge-bitcoin = { path = "../../xbridge/bitcoin", default_features = false }

base58 = { version = "0.1", optional = true }

[features]
default = ["std"]
std=[
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    "parity-codec-derive/std",
    "substrate-primitives/std",
    "sr-std/std",
    "sr-io/std",
    "sr-primitives/std",
    "srml-support/std",
    "srml-system/std",
    "srml-balances/std",
    "srml-timestamp/std",
    "srml-consensus/std",

    # xrml
    "xrml-xassets-assets/std",
    "xrml-xassets-records/std",

    # bridge
    "xrml-xbridge-bitcoin/std",

    # other
    "base58",
]
