[package]
name = "xrml-xdex-spot"
version = "0.4.0"
authors = ["Chainpool <https://www.chainx.org>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default_features = false }
runtime_io = { package = "sr-io", git = "https://github.com/chainpool/substrate", default_features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default_features = false }
runtime_support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default_features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default_features = false }
balances = { package = "srml-balances", git = "https://github.com/chainpool/substrate", default_features = false }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", default_features = false }
indices = { package = "srml-indices", git = "https://github.com/chainpool/substrate", default_features = false }
timestamp = { package ="srml-timestamp", git = "https://github.com/chainpool/substrate", default_features = false }

# cxrml module
xsystem = { package = "xrml-xsystem", path = "../../xsystem", default-features = false }
xaccounts = { package = "xrml-xaccounts", path = "../../xaccounts", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default_features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xassets/assets", default_features = false }
xbitcoin = { package = "xrml-bridge-bitcoin", path = "../../xbridge/bitcoin", default-features = false }
xrecords = { package = "xrml-xassets-records", path = "../../xassets/records", default-features = false }

[dev-dependencies]
fee_manager = { package = "xrml-fee-manager", path = "../../xfee/manager", default-features = false }

[features]
default = ["std"]
std=[
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    "substrate-primitives/std",
    "rstd/std",
    "runtime_io/std",
    "system/std",
    "primitives/std",
    "runtime_support/std",
    "xsystem/std",
    "balances/std",
    "xaccounts/std",
    "xsupport/std",
    "xassets/std",
    "xrecords/std",
    "xbitcoin/std",
]
